In [11]:
import pandas as pd
import numpy as np

## Foundations for efficiencies

Built-in functions

In [3]:
# Range
# Range from 0-5
print(list(range(6)))

# List of odd numbers from 1 to 11
print([*range(1,12,2)])

[0, 1, 2, 3, 4, 5]
[1, 3, 5, 7, 9, 11]


In [5]:
# Enumerate
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
indexed_names = []

# Simple example
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# List comprehension
print([(i,name) for i,name in enumerate(names)])

# list starting with one
print([*enumerate(names, 1)])

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


In [8]:
# Map
names_map  = map(str.upper, names)
print([*names_map])

# Lambda
print(list(map(lambda x: x.lower(), ["A", "B", "C"])))

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
['a', 'b', 'c']


In [14]:
# Numpy
nums = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]
nums = np.array(nums)

#Numpy array is faster than python List because of npArray homogenity (Same type)
print(nums.dtype)

#Numpy has special indexing
# Example Print second row of nums
print(nums[:,1])

#Numpy array has boolean indexing
# Example Print all values large then 6
print(nums[nums > 6])

#Numpy allow to do math operations easier
print(nums + 1)

int32
[2 7]
[ 7  8  9 10]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]


## Timing and profiling code

Comparer times with timeit

In [21]:
# Compare Unpack with Copr
%timeit nums_list_comp = [num for num in range(51)]

%timeit nums_list_unpack = [*range(51)]

3.92 µs ± 688 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.12 µs ± 57.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
# Specify runTimes and Loops
heroes = ['A','B','C','D','E','F']
%timeit -r5 -n25 set(heroes)

902 ns ± 98.8 ns per loop (mean ± std. dev. of 5 runs, 25 loops each)


Profiling Using Python line_profiling (Remember to PIP)

In [22]:
%load_ext line_profiler

In [24]:
# Random Function
def convert_units(heroes, heights, weights):

    new_hts = [ht * 0.39370  for ht in heights]
    new_wts = [wt * 2.20462  for wt in weights]

    hero_data = {}

    for i,hero in enumerate(heroes):
        hero_data[hero] = (new_hts[i], new_wts[i])

    return hero_data

heroes = ['A', 'B', 'C']
heights = [1.7, 1.8, 1.9]
weights = [80, 87, 130]

In [25]:
%lprun -f convert_units convert_units(heroes, heights, weights)

Timer unit: 1e-07 s

Total time: 3.14e-05 s
File: <ipython-input-24-36b8cb35486a>
Function: convert_units at line 2

Line #      Hits         Time  Per Hit   % Time  Line Contents
     2                                           def convert_units(heroes, heights, weights):
     3                                           
     4         1        102.0    102.0     32.5      new_hts = [ht * 0.39370  for ht in heights]
     5         1         69.0     69.0     22.0      new_wts = [wt * 2.20462  for wt in weights]
     6                                           
     7         1         11.0     11.0      3.5      hero_data = {}
     8                                           
     9         4         75.0     18.8     23.9      for i,hero in enumerate(heroes):
    10         3         49.0     16.3     15.6          hero_data[hero] = (new_hts[i], new_wts[i])
    11                                           
    12         1          8.0      8.0      2.5      return hero_data